### PR TITLE
GJValueTween Class Members & Parameter Names

### PR DESCRIPTION
**Pull request by CallocGD**
This was Acuroso's Final Contribution to my project before he left and because of that, I wanted to make this pull request as grandiose as possible. I have added the class members he had found me that make the step function operate the way that it does. 
I am a little confused about what the last class member was supposed to be but I can uncomment that part as requested if it's name has been figured out in the future.

### CODE REVIEW

**Comment by kynex7510** [comment]
Last bool is whether the action is finished or not. Can you add that?

**Comment by CallocGD** [comment]
I can try to but it may take a while to figure out what exactly it is.

**Comment by kynex7510** [comment]
I just told you what it is.

**Comment by CallocGD** [comment]
@kynex7510 Updated members with you suggestions now...

**Pull request merged**
