### PR TITLE
windows AchievementsLayer and AchievementManager

### PR DESCRIPTION
**Pull request by maromalo**
with a few extras

### CODE REVIEW

**Comment by Cvolton** [comment]
how are button callbacks inlined

**Comment by hiimjustin000** [comment]
Ghidra didn't catch them so they think they're inlined

**Comment by maromalo** [comment]
@Cvolton 
windows:
javaw_1719251105

android:
javaw_1719251133
javaw_1719251148

if i was better at this i would've defined them in the broma file

**Comment by matcool** [comment]
just check devtools, actual button callbacks can never be inlined

**Comment by maromalo** [comment]
i'm dumb, added them
pretty sure the other ones **are** inlined tho

**Pull request merged**
