### PR TITLE
dont blame me both zmx and dankmeme said i can do this for globals

### PR DESCRIPTION
**Pull request by TheSillyDoggo**

### CODE REVIEW

**Comment by altalk23** [comment]
yeah no

**Comment by FireMario211** [comment]
i dont like this...

**Comment by TheSillyDoggo** [comment]
> yeah no

How do I write and read a global variable?

**Comment by altalk23** [comment]
girl that is not the same, youre forgetting android

**Comment by TheSillyDoggo** [comment]
On android the functions aren't inline

**Comment by TheSillyDoggo** [comment]
nvm i just added these functions into the mod instead of bindings

**Pull request closed without merging**
