### PR TITLE
Add m_onlineType (Levels or Lists) to GameManager

### PR DESCRIPTION
**Pull request by hiimjustin000**
Windows is perfectly fine, the other two (Mac and Android32) are educated guesses, the other (Android64) I don't have, so I can't find that address.

Actions are not running properly, either something on my end or a bug. Please suggest fixes.

### CODE REVIEW

**Comment by Cvolton** [comment]
how did you find this?

**Comment by hiimjustin000** [comment]
Well I found the different addresses of `m_unkBool12` and used `CreatorLayer::onOnlineLevels` to determine `m_browseType`

**Comment by hiimjustin000** [comment]
Android64, Android32, macOS, and Windows finished. Haven't tested, though.

**Comment by hiimjustin000** [comment]
Before merging this pull request, someone test these new bindings on Android and Mac. I haven't had a MacBook since 2019.

**Comment by Cvolton** [comment]
weird because GameManager should be complete

also I checked the same function and `m_unkSize4_17` appears to be the search type, this is supported by a brief test i did by logging the value

**Comment by hiimjustin000** [comment]
> also I checked the same function and `m_unkSize4_17` appears to be the search type, this is supported by a brief test i did by logging the value

Well that's not the case in Ghidra. It's actually called `offset_0x3d0` and it's in `CreatorLayer::onOnlineLevels`. `m_unkSize4_17` is `offset_0x2ac` and it's not mentioned anywhere in that function. I actually tested the offset of `0x3d4` in my mod and it works perfectly fine, so I'm confident this is correct.

**Comment by hiimjustin000** [comment]
Plus, I checked `m_unkSize4_17` in Ghidra, and turns out, that's the index of the player's trail. Not the ship fire, but the trail.

**Comment by Cvolton** [comment]
if you used syncbromascript to import your members, they're misaligned, since it doesn't properly import any inherited classes. `m_unkSize4_17` is at 0x3d4

image

**Comment by hiimjustin000** [comment]
I wish you would have told me this earlier

**Pull request closed without merging**
