### PR TITLE
AnimatedShopKeeper

### PR DESCRIPTION
**Pull request by hiimjustin000**
**Some things are better left alone.**

This has been properly tested.

### CODE REVIEW

**Comment by Cvolton** [comment]
it broke mac build btw i had to fix that

**Comment by hiimjustin000** [comment]
gfd

**Comment by HJfod** [comment]
do not merge this pullrequest it is DEVIL'S DOING!!!!! the DEVIL IS IN THE PULL REQUEST YOU MUST NOT MERGE

**Comment by SpaghettDev** [comment]
too late the devil now lives in geometry dash bindings

**Pull request merged**
